version: "3.4"
services:

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    image: collectionapp
    container_name: collectionapp
    restart: always